services:
  phoenixd:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: phoenixd # Eliminar linea para escalado
    # Descomentar para exponer fuera del host
    ports:
      - "127.0.0.1:9740:9740"   # API HTTP (solo localhost)
    # - "9735:9735"   # P2P Lightning público (opcional)
    networks:
      - backend
    volumes:
      - ./data:/home/phoenix/.phoenix
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-lc", "exec 3<>/dev/tcp/127.0.0.1/9740"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  backend:
    external: true
    name: backend