services:
  phoenixd:
    build:
      context: .
      args:
        PHOENIXD_BRANCH: v0.6.2
    image: local/phoenixd:0.6.2
    container_name: phoenixd
    restart: unless-stopped
    networks:
      - backend
    command: ["--http-bind-ip=0.0.0.0","--auto-liquidity=10m"]
    expose:
      - "9740"
    volumes:
      - "phoenixd_datadir:/phoenix/.phoenix"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=16m
volumes:
  phoenixd_datadir:

networks:
  backend:
    external: true
    name: backend